export const languages = [
  { key: "de", fileName: "german" },
  { key: "en", fileName: "english" },
];

export const itemTypes = [
  {
    key: "harboroffice",
    labelId: 4065,
    icon: "icon_harbour_kontor_0",
    fileNames: ["harborofficeitem"],
  },
  {
    key: "guildhouse",
    labelId: 2346,
    icon: "icon_guildhouse_0",
    fileNames: ["guildhouseitem"],
  },
  {
    key: "townhall",
    labelId: 2347,
    icon: "icon_townhall_0",
    fileNames: ["townhallitem"],
  },
  {
    key: "arctic-lodge",
    labelId: 115353,
    icon: "icon_community_lodge_0",
    fileNames: ["lodgeitem"],
  },
  {
    key: "ship",
    labelId: 2342,
    icon: "icon_ship_0",
    fileNames: ["shipspecialist", "vehicleitem", "warshipitem"],
    hidden: true,
  },
];
export const expeditionThreats = [
  {
    key: "might",
    labelId: 800004,
    icon: "icon_threat_navalbattle_tint",
  },
  {
    key: "faith",
    labelId: 800028,
    icon: "icon_church_2d",
  },
  {
    key: "diplomacy",
    labelId: 800029,
    icon: "icon_diplomacy_option_negotiate",
  },
  {
    key: "hunting",
    labelId: 800030,
    icon: "ship_info/icon_accuracy",
  },
  {
    key: "medicine",
    labelId: 800031,
    icon: "icon_threat_diseases_tint",
  },
  {
    key: "melee",
    labelId: 800032,
    icon: "icon_threat_melee_tint",
  },
  {
    key: "navigation",
    labelId: 800033,
    icon: "icon_threat_navigation_tint",
  },
  {
    key: "crafting",
    labelId: 800034,
    icon: "icon_threat_crafting_tint",
  },
  {
    key: "perkformerpirate",
    labelId: 191598,
  },
  {
    key: "perkmale",
    labelId: 15797,
  },
  {
    key: "perkfemale",
    labelId: 15798,
  },
  {
    key: "perkzoologist",
    labelId: 9998,
  },
  {
    key: "perkhypnotist",
    labelId: 3929,
  },
  {
    key: "perkanthropologist",
    labelId: 3928,
  },
  {
    key: "perkarcheologist",
    labelId: 12262,
  },
  {
    key: "perkentertainer",
    labelId: 12261,
  },
  {
    key: "perkpolyglot",
    labelId: 12266,
  },
  {
    key: "perkjackofalltraits",
    labelId: 12260,
  },
  {
    key: "perkdiver",
    labelId: 3931,
  },
  {
    key: "perkmilitaryship",
    labelId: 3932,
  },
];
export const rarities = [
  { key: "common", labelId: 118002, color: "#FFFFFE" },
  { key: "uncommon", labelId: 118003, color: "#659E2C" },
  { key: "rare", labelId: 118004, color: "#3E5495" },
  { key: "epic", labelId: 118005, color: "#A563A6" },
  { key: "legendary", labelId: 118006, color: "#C76936" },
  { key: "narrative", labelId: 19850, color: "#4A385F" },
];
export const upgrades = [
  { key: "ProductivityUpgrade", labelId: 118000, valueIs: "positive" },
  { key: "MaintenanceUpgrade", labelId: 2320, valueIs: "negative" },
  { key: "ReplaceInputs", labelId: 20081 },
  {
    key: "AttractivenessUpgrade",
    labelId: 145011,
    valueIs: "positive",
  },
  { key: "AdditionalOutput", labelId: 20074 },
  { key: "ReplacingWorkforce", labelId: 12480 },
  { key: "WorkforceAmountUpgrade", labelId: 12337 },
  { key: "ModuleLimitPercent", labelId: 12075 },
  { key: "NeededAreaPercentUpgrade", labelId: 15319 },
  {
    key: "IncidentFireIncreaseUpgrade",
    labelId: 12225,
    valueIs: "negative",
  },
  { key: "ProvideIndustrialization", labelId: 12485 },
  {
    key: "IncidentExplosionIncreaseUpgrade",
    labelId: 14292,
    valueIs: "negative",
  },
  {
    key: "IncidentRiotIncreaseUpgrade",
    labelId: 14290,
    valueIs: "negative",
  },
  { key: "PipeCapacityUpgrade", labelId: 127395 },
  { key: "RiotInfluenceUpgrade", labelId: 14513 },
  { key: "AdditionalHappiness", labelId: 12314, valueIs: "positive" },
  { key: "ResolverUnitDecreaseUpgrade", labelId: 21508 },
  { key: "ResolverUnitMovementSpeedUpgrade", labelId: 12012 },
  { key: "ResolverUnitCountUpgrade", labelId: 3897 },
  { key: "AddedFertility", labelId: 23371 },
  { key: "AttractivenessPositive", labelId: 145011 },
  {
    key: "PublicServiceFullSatisfactionDistance",
    labelId: 2321,
    valueIs: "positive",
  },
  { key: "InputBenefitModifier", labelId: 12690 },
  { key: "ResidentsUpgrade", labelId: 2322 },
  { key: "TaxModifierInPercent", labelId: 12677, valueIs: "positive" },
  {
    key: "IncidentIllnessIncreaseUpgrade",
    labelId: 12226,
    valueIs: "negative",
  },
  { key: "NeedProvideNeedUpgrade", labelId: 12315 },
  { key: "StressUpgrade", labelId: 2323 },
  { key: "GoodConsumptionUpgrade", labelId: 21386 },
  {
    key: "WorkforceModifierInPercent",
    labelId: 12676,
    valueIs: "positive",
  },
  { key: "InputAmountUpgrade", labelId: 23509 },
  { key: "SpecialUnitHappinessThresholdUpgrade", labelId: 21593 },
  { key: "BlockHostileTakeover", labelId: 15801 },
  { key: "SpawnProbabilityFactor", labelId: 20084 },
  { key: "ConstructionCostInPercent", labelId: 12723 },
  { key: "AddAssemblyOptions", labelId: 21494 },
  { key: "BaseDamageUpgrade", labelId: 2334 },
  { key: "AttackSpeedUpgrade", labelId: 2336 },
  { key: "Hitpoints", labelId: 2333 },
  { key: "GenProbability", labelId: 12920 },
  { key: "GenPool", labelId: 12315 },
  { key: "BlockBuyShare", labelId: 15802 },
  { key: "HappinessIgnoresMorale", labelId: 15811 },
  { key: "MaxHitpointsUpgrade", labelId: 1154 },
  { key: "AttackRangeUpgrade", labelId: 12021 },
  { key: "HitpointDamage", labelId: 2334 },
  { key: "LineOfSightRangeUpgrade", labelId: 15266 },
  { key: "SelfHealUpgrade", labelId: 15195 },
  { key: "SelfHealPausedTimeIfAttackedUpgrade", labelId: 15196 },
  { key: "HealRadiusUpgrade", labelId: 15264 },
  { key: "HealPerMinuteUpgrade", labelId: 15265 },
  { key: "HealBuildingsPerMinuteUpgrade", labelId: 15265 },
  { key: "AccuracyUpgrade", labelId: 12062 },
  { key: "PierSpeedUpgrade", labelId: 15197 },
  { key: "DamageReceiveFactor", labelId: 19136 },
  { key: "MoraleDamage", labelId: 9499 },
  { key: "IncidentArcticIllnessIncreaseUpgrade", labelId: 22982 },
  { key: "HeatRangeUpgrade", labelId: 2321 },
  { key: "ForwardSpeedUpgrade", labelId: 2339 },
  { key: "IgnoreDamageFactorUpgrade", labelId: 15262 },
  { key: "LoadingSpeedUpgrade", labelId: 15197 },
  { key: "IgnoreWeightFactorUpgrade", labelId: 15261 },
  { key: "MaintainanceUpgrade", labelId: 2320 },
  { key: "ActiveTradePriceInPercent", labelId: 15198 },
];
